import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const storeSource = readFileSync(new URL('./store.jsx', import.meta.url), 'utf8')
const screenDataSource = readFileSync(new URL('./hooks/useScreenData.js', import.meta.url), 'utf8')
const homeSource = readFileSync(new URL('./screens/Home.jsx', import.meta.url), 'utf8')
const settlementSource = readFileSync(new URL('./screens/SettlementPeriod.jsx', import.meta.url), 'utf8')
const settingsSource = readFileSync(new URL('./screens/Settings.jsx', import.meta.url), 'utf8')
const appSource = readFileSync(new URL('./app-v2.jsx', import.meta.url), 'utf8')
const newGroupSource = readFileSync(new URL('./screens/NewGroup.jsx', import.meta.url), 'utf8')
const migrationSource = readFileSync(new URL('../supabase/migrations/20260523000001_profiles_identity.sql', import.meta.url), 'utf8')
const expenseGroupRpcMigration = readFileSync(new URL('../supabase/migrations/20260525000003_expense_group_member_rpcs.sql', import.meta.url), 'utf8')
const memberBillShareMigration = readFileSync(new URL('../supabase/migrations/20260526000001_member_bill_share_tokens.sql', import.meta.url), 'utf8')
const expenseGroupExpenseRpcMigration = readFileSync(new URL('../supabase/migrations/20260526000002_expense_group_expense_rpcs.sql', import.meta.url), 'utf8')
const expenseGroupRoleRpcMigration = readFileSync(new URL('../supabase/migrations/20260526000003_expense_group_role_rpcs.sql', import.meta.url), 'utf8')
const profileGroupIdsMigration = readFileSync(new URL('../supabase/migrations/20260526000004_profile_group_ids.sql', import.meta.url), 'utf8')
const adminGroupManagementMigration = readFileSync(new URL('../supabase/migrations/20260529000002_admin_group_management.sql', import.meta.url), 'utf8')

test('profiles migration creates central identity and links members', () => {
  assert.match(migrationSource, /CREATE TABLE IF NOT EXISTS public\.profiles/)
  assert.match(migrationSource, /ALTER TABLE public\.members[\s\S]*ADD COLUMN IF NOT EXISTS profile_id uuid/)
  assert.match(migrationSource, /ADD COLUMN IF NOT EXISTS expense_active boolean DEFAULT true/)
  assert.match(migrationSource, /UPDATE public\.members[\s\S]*SET expense_active = false[\s\S]*member_type IN \('casual', 'guest', 'vanglai', 'vãng lai'\)/)
  assert.match(migrationSource, /REFERENCES public\.profiles\(id\)/)
  assert.match(migrationSource, /INSERT INTO public\.profiles/)
  assert.match(migrationSource, /UPDATE public\.members m[\s\S]*SET profile_id = p\.id/)
  assert.match(migrationSource, /ALTER COLUMN profile_id SET NOT NULL/)
  assert.match(migrationSource, /CREATE TRIGGER members_ensure_profile/)
  assert.match(migrationSource, /CREATE POLICY profiles_select/)
  assert.match(migrationSource, /CREATE POLICY profiles_update/)
})

test('member bill share migration creates scoped expiring public tokens', () => {
  assert.match(memberBillShareMigration, /CREATE TABLE IF NOT EXISTS public\.member_bill_share_tokens/)
  assert.match(memberBillShareMigration, /token text NOT NULL UNIQUE/)
  assert.match(memberBillShareMigration, /group_id uuid NOT NULL REFERENCES public\.groups\(id\)/)
  assert.match(memberBillShareMigration, /member_id uuid NOT NULL REFERENCES public\.members\(id\)/)
  assert.match(memberBillShareMigration, /expires_at timestamptz NOT NULL/)
  assert.match(memberBillShareMigration, /created_by uuid REFERENCES public\.members\(id\)/)
  assert.match(memberBillShareMigration, /CREATE OR REPLACE FUNCTION public\.create_member_bill_share_token/)
  assert.match(memberBillShareMigration, /CREATE OR REPLACE FUNCTION public\.get_member_bill_share/)
  assert.match(memberBillShareMigration, /WHERE mbst\.token = p_token[\s\S]*mbst\.expires_at > now\(\)/)
  assert.match(memberBillShareMigration, /jsonb_build_object\([\s\S]*'groupId', v_share\.group_id[\s\S]*'memberId', v_share\.member_id/)
  assert.match(memberBillShareMigration, /'paymentTarget', jsonb_build_object/)
  assert.match(memberBillShareMigration, /'bankName', \([\s\S]*SELECT treasurer\.bank_name/)
  assert.match(memberBillShareMigration, /'bankAccount', \([\s\S]*SELECT treasurer\.bank_account/)
  assert.match(memberBillShareMigration, /'bankAccountName', \([\s\S]*SELECT treasurer\.bank_account_name/)
  assert.match(memberBillShareMigration, /REVOKE ALL ON public\.member_bill_share_tokens FROM anon/)
  assert.match(memberBillShareMigration, /GRANT EXECUTE ON FUNCTION public\.get_member_bill_share\(text\) TO anon/)
})

test('member bill share token creation resolves the actor inside the target expense group profile', () => {
  assert.match(memberBillShareMigration, /v_actor_member_id uuid/)
  assert.match(memberBillShareMigration, /CREATE OR REPLACE FUNCTION public\.create_member_bill_share_token[\s\S]*SET search_path = public, extensions/)
  assert.match(memberBillShareMigration, /WITH current_actor AS \(/)
  assert.match(memberBillShareMigration, /actor\.profile_id IS NOT NULL AND creator\.profile_id = actor\.profile_id/)
  assert.match(memberBillShareMigration, /creator\.id = actor\.id/)
  assert.match(memberBillShareMigration, /created_by\)[\s\S]*VALUES \(v_token, p_group_id, p_member_id[\s\S]*v_actor_member_id\)/)
})

test('expense group expense RPC saves expenses through the current profile membership', () => {
  assert.match(expenseGroupExpenseRpcMigration, /CREATE OR REPLACE FUNCTION public\.create_expense_group_expense/)
  assert.match(expenseGroupExpenseRpcMigration, /public\.is_member_of_expense_group\(p_group_id\)/)
  assert.match(expenseGroupExpenseRpcMigration, /actor\.profile_id IS NOT NULL[\s\S]*m\.profile_id = actor\.profile_id/)
  assert.match(expenseGroupExpenseRpcMigration, /submitted_by_member_id[\s\S]*v_actor_member_id/)
  assert.match(expenseGroupExpenseRpcMigration, /paid_by_member_id[\s\S]*p_paid_by_member_id/)
  assert.match(expenseGroupExpenseRpcMigration, /INSERT INTO public\.expense_participants/)
  assert.match(expenseGroupExpenseRpcMigration, /GRANT EXECUTE ON FUNCTION public\.create_expense_group_expense/)
})

test('expense group expense RPC auto-approves creator and treasurer submissions', () => {
  assert.match(expenseGroupRoleRpcMigration, /CREATE OR REPLACE FUNCTION public\.is_expense_group_admin/)
  assert.match(expenseGroupRoleRpcMigration, /m\.role = 'treasurer'/)
  assert.match(expenseGroupRoleRpcMigration, /g\.created_by = p_member_id/)
  assert.match(expenseGroupRoleRpcMigration, /g\.created_by = m\.profile_id/)
  assert.match(expenseGroupRoleRpcMigration, /public\.is_expense_group_admin\(p_group_id, v_actor_member_id\)/)
  assert.match(expenseGroupRoleRpcMigration, /v_existing\.submitted_by_member_id = v_actor_member_id[\s\S]*AND v_existing\.status IN \('pending', 'rejected', 'declined'\)/)
  assert.match(expenseGroupRoleRpcMigration, /status = CASE[\s\S]*WHEN v_is_admin THEN 'approved'[\s\S]*ELSE 'pending'/)
  assert.match(expenseGroupRoleRpcMigration, /reviewed_by_member_id = CASE[\s\S]*WHEN v_is_admin THEN v_actor_member_id[\s\S]*ELSE NULL/)
  assert.match(expenseGroupRoleRpcMigration, /THEN 'approved'/)
})

test('expense review RPC resolves the reviewer inside the target expense group profile', () => {
  assert.match(expenseGroupRoleRpcMigration, /CREATE OR REPLACE FUNCTION public\.review_expense_group_expense/)
  assert.match(expenseGroupRoleRpcMigration, /p_status NOT IN \('approved', 'rejected', 'declined'\)/)
  assert.match(expenseGroupRoleRpcMigration, /actor\.profile_id IS NOT NULL[\s\S]*m\.profile_id = actor\.profile_id/)
  assert.match(expenseGroupRoleRpcMigration, /public\.is_expense_group_admin\(p_group_id, v_actor_member_id\)/)
  assert.match(expenseGroupRoleRpcMigration, /UPDATE public\.expenses[\s\S]*status = p_status/)
  assert.match(expenseGroupRoleRpcMigration, /GRANT EXECUTE ON FUNCTION public\.review_expense_group_expense\(uuid, uuid, text\) TO anon/)
})

test('delete expense group RPC resolves the actor inside the target group profile', () => {
  assert.match(expenseGroupRoleRpcMigration, /CREATE OR REPLACE FUNCTION public\.delete_expense_group/)
  assert.match(expenseGroupRoleRpcMigration, /actor\.profile_id IS NOT NULL[\s\S]*m\.profile_id = actor\.profile_id/)
  assert.match(expenseGroupRoleRpcMigration, /public\.is_expense_group_admin\(p_group_id, v_actor_member_id\)/)
  assert.match(expenseGroupRoleRpcMigration, /UPDATE public\.groups[\s\S]*deleted_at = now\(\)[\s\S]*WHERE id = p_group_id/)
  assert.match(expenseGroupRoleRpcMigration, /GRANT EXECUTE ON FUNCTION public\.delete_expense_group\(uuid\) TO anon/)
})

test('delete expense RPC resolves the actor inside the target expense group profile', () => {
  assert.match(expenseGroupRoleRpcMigration, /CREATE OR REPLACE FUNCTION public\.delete_expense_group_expense/)
  assert.match(expenseGroupRoleRpcMigration, /p_expense_id uuid/)
  assert.match(expenseGroupRoleRpcMigration, /p_group_id uuid/)
  assert.match(expenseGroupRoleRpcMigration, /WITH current_actor AS \(/)
  assert.match(expenseGroupRoleRpcMigration, /actor\.profile_id IS NOT NULL[\s\S]*m\.profile_id = actor\.profile_id/)
  assert.match(expenseGroupRoleRpcMigration, /public\.is_expense_group_admin\(p_group_id, v_actor_member_id\)/)
  assert.match(expenseGroupRoleRpcMigration, /v_existing\.submitted_by_member_id = v_actor_member_id[\s\S]*v_existing\.status IN \('pending', 'rejected', 'declined'\)/)
  assert.match(expenseGroupRoleRpcMigration, /DELETE FROM public\.expense_participants/)
  assert.match(expenseGroupRoleRpcMigration, /DELETE FROM public\.expenses/)
  assert.match(expenseGroupRoleRpcMigration, /GRANT EXECUTE ON FUNCTION public\.delete_expense_group_expense\(uuid, uuid\) TO anon/)
})

test('set expense group member role RPC resolves the actor inside the target group profile', () => {
  assert.match(expenseGroupRoleRpcMigration, /CREATE OR REPLACE FUNCTION public\.set_expense_group_member_role/)
  assert.match(expenseGroupRoleRpcMigration, /p_role NOT IN \('member', 'treasurer'\)/)
  assert.match(expenseGroupRoleRpcMigration, /actor\.profile_id IS NOT NULL[\s\S]*m\.profile_id = actor\.profile_id/)
  assert.match(expenseGroupRoleRpcMigration, /public\.is_expense_group_admin\(p_group_id, v_actor_member_id\)/)
  assert.match(expenseGroupRoleRpcMigration, /UPDATE public\.members[\s\S]*role = p_role[\s\S]*WHERE id = p_member_id[\s\S]*AND group_id = p_group_id/)
  assert.match(expenseGroupRoleRpcMigration, /GRANT EXECUTE ON FUNCTION public\.set_expense_group_member_role\(uuid, uuid, text\) TO anon/)
})

test('create group keeps the creator on the current profile identity', () => {
  assert.match(expenseGroupRoleRpcMigration, /v_actor_profile_id uuid/)
  assert.match(expenseGroupRoleRpcMigration, /SELECT profile_id[\s\S]*INTO v_actor_profile_id/)
  assert.match(expenseGroupRoleRpcMigration, /INSERT INTO public\.members \(group_id, name, role, profile_id\)/)
  assert.match(expenseGroupRoleRpcMigration, /CASE WHEN v_creator_id IS NULL THEN v_actor_profile_id ELSE NULL END/)
})

test('store fetches profiles and merges profile fields into members', () => {
  assert.match(storeSource, /profiles:\s*\[\]/)
  assert.match(storeSource, /prR/)
  assert.match(storeSource, /sb\.from\('profiles'\)\.select\('\*'\)/)
  assert.match(storeSource, /profiles:\s*prR\.data \|\| \[\]/)
  assert.match(storeSource, /profiles = \[\]/)
  assert.match(storeSource, /const profilesById = new Map/)
  assert.match(storeSource, /const profile = profilesById\.get\(String\(m\.profile_id \|\| ''\)\)/)
  assert.match(storeSource, /const memberName = String\(m\.name \|\| profile\?\.name \|\| ''\)\.trim\(\)/)
  assert.match(storeSource, /profileId: m\.profile_id/)
  assert.match(storeSource, /name: memberName/)
  assert.match(storeSource, /bankName: profile\?\.bank_name \|\| m\.bank_name \|\| ''/)
  assert.match(storeSource, /profiles: normalProfiles/)
})

test('ADD_MEMBER links existing profile if provided, skips profile creation', () => {
  const addMemberBlock = storeSource.match(/case 'ADD_MEMBER': \{[\s\S]*?return newMember[\s\S]*?\n      \}/)?.[0] || ''
  assert.match(storeSource, /async function ensureProfileForMember\(sb, member\) \{/)
  assert.match(addMemberBlock, /const profileId = member\?\.profileId \|\| member\?\.profile_id/)
  assert.match(addMemberBlock, /memberInsertRow\(groupId, \{ \.\.\.member, profileId \}, member\.role \|\| 'member'\)/)
})

test('new group flow can include existing profiles', () => {
  assert.match(screenDataSource, /function buildNewGroupData\(state = \{\}\)/)
  assert.match(screenDataSource, /profileOptions: buildProfileOptions\(state\)/)
  assert.match(screenDataSource, /groupTypeOptions: \[/)
  assert.match(screenDataSource, /dedupeProfilesFromMembers\(safeArray\(state\?\.members\), profiles\)/)
  assert.match(screenDataSource, /\.filter\(isActiveMember\)/)
  assert.match(newGroupSource, /const \[selectedProfileIds, setSelectedProfileIds\] = useState/)
  assert.match(newGroupSource, /const \[profileQuery, setProfileQuery\] = useState\(''\)/)
  assert.match(newGroupSource, /profileOptions/)
  assert.match(newGroupSource, /filteredProfileOptions/)
  assert.match(newGroupSource, /placeholder="Tìm vài ký tự để lọc thành viên"/)
  assert.match(newGroupSource, /maxHeight: 360/)
  assert.match(newGroupSource, /toggleProfile/)
  assert.match(newGroupSource, /profileIds: selectedProfileIds/)
  assert.match(storeSource, /const profileIds = safeArray\(action\.profileIds \?\? group\.profileIds\)/)
  assert.match(storeSource, /selectedProfiles = profileIds/)
  assert.match(storeSource, /profile_id: selectedProfile\.profileId \|\| selectedProfile\.id/)
})

test('screen data exposes profile aggregation helpers for home and monthly close', () => {
  assert.match(screenDataSource, /function profileIdForMember\(memberId, members\) \{/)
  assert.match(screenDataSource, /function memberIdsForProfile\(profileId, members\) \{/)
  assert.match(screenDataSource, /function aggregateBalancesByProfile\(sourceBalances, members\) \{/)
  assert.match(screenDataSource, /const sourceBalances = buildHomeSourceBalances/)
  assert.match(screenDataSource, /const rawProfileBreakdown = aggregateBalancesByProfile\(sourceBalances, members\)/)
  assert.match(screenDataSource, /const profileBreakdown = adjustedProfileBreakdownForPayments\(state, rawProfileBreakdown, members, today\)/)
  assert.match(screenDataSource, /profileBreakdown,/)
  assert.match(screenDataSource, /memberName: me\?\.displayName \|\| me\?\.name \|\| state\?\.currentUserName \|\| 'Thành viên'/)
  assert.match(screenDataSource, /payForRows: safeArray\(profileBreakdown\)/)
  assert.match(screenDataSource, /\.filter\(row => Number\(row\.amount\) < 0\)/)
  assert.match(screenDataSource, /const monthlySourceBalances = buildMonthlySourceBalances/)
  assert.match(screenDataSource, /profileBreakdown: aggregateBalancesByProfile\(monthlySourceBalances, members\)/)
})

test('home renders source breakdown for the current profile', () => {
  assert.match(screenDataSource, /currentProfileId: profileIdForMember\(currentUserId, members\)/)
  assert.match(screenDataSource, /const rawSourceBreakdown = currentProfileSourceBreakdown\(sourceBalances, currentUserId, members\)/)
  assert.match(screenDataSource, /const sourceBreakdown = paymentSummary\.sourceBreakdown/)
  assert.match(screenDataSource, /function currentProfileSourceBreakdown\(sourceBalances, currentUserId, members\) \{/)
  assert.match(homeSource, /<SourceBreakdown[\s\S]*sources=\{d\.sourceBreakdown \|\| \[\]\}[\s\S]*totalBalance=\{d\.totalBalance\}[\s\S]*paymentStatus=\{d\.paymentSummary\?\.paymentStatus\}[\s\S]*onOpenPayment=\{\(\) => setPaymentSheetOpen\(true\)\}[\s\S]*onAction=\{onAction\}[\s\S]*\/>/)
  assert.match(homeSource, /function SourceBreakdown\(\{ sources, totalBalance = 0, balanceLabel = '', owedTo = 0, paymentStatus = '', onOpenPayment, onAction \}\) \{/)
  assert.match(homeSource, /Theo nguồn tiền/)
  assert.match(homeSource, /source\.sourceLabel/)
  assert.match(homeSource, /source\.sourceType === 'pickleball'/)
  assert.match(homeSource, /onAction\?\.\('tab', 'pickleball'\)/)
  assert.match(homeSource, /onAction\?\.\('open', source\.sourceId\)/)
})

test('monthly close renders one profile bill with source breakdown rows', () => {
  assert.match(screenDataSource, /const monthlySourceBalances = buildGlobalMonthlySourceBalances\(state, monthDate\)/)
  assert.match(screenDataSource, /profileBills: buildProfileBillRows\(monthlySourceBalances, members\)/)
  assert.match(screenDataSource, /function buildGlobalMonthlySourceBalances\(state, monthDate\) \{/)
  assert.match(screenDataSource, /function buildProfileBillRows\(sourceBalances, members\) \{/)
  assert.match(settlementSource, /const profileBills = d\.profileBills \|\| \[\]/)
  assert.match(settlementSource, /<ProfileBillList bills=\{profileBills\} onAction=\{onAction\} \/>/)
  assert.match(settlementSource, /function ProfileBillList\(\{ bills, onAction \}\) \{/)
  assert.match(settlementSource, /Bill tháng theo người/)
  assert.match(settlementSource, /sources\.map/)
})

test('monthly bill screen replaces hard close with per-member bill sharing', () => {
  assert.match(settlementSource, /Gửi bill \{d\.monthLabel\}/)
  assert.match(settlementSource, /Bill tháng theo người/)
  assert.match(settlementSource, /<ProfileBillList bills=\{profileBills\} onAction=\{onAction\} \/>/)
  assert.match(settlementSource, /function ProfileBillList\(\{ bills, onAction \}\) \{/)
  assert.match(settlementSource, /onAction\?\.\('createMemberBillShare'/)
  assert.match(settlementSource, /Copy bill/)
  assert.doesNotMatch(settlementSource, /Xác nhận chốt sổ/)
  assert.doesNotMatch(settlementSource, /không thể sửa/)
  assert.doesNotMatch(settlementSource, /confirmClose/)
})

test('settings hides profile link management from the app UI while keeping profile RPC handlers available', () => {
  assert.match(screenDataSource, /profileSync: buildProfileSyncData\(state, me\)/)
  assert.match(screenDataSource, /function buildProfileSyncData\(state, me\) \{/)
  assert.doesNotMatch(settingsSource, /Danh bạ liên thông/)
  assert.doesNotMatch(settingsSource, /Có thể gộp vào danh bạ này/)
  assert.doesNotMatch(settingsSource, /function ProfileSyncSection/)
  assert.doesNotMatch(settingsSource, /function ProfileMembershipRow/)
  assert.doesNotMatch(settingsSource, /onAction\?\.\('linkProfile'/)
  assert.doesNotMatch(settingsSource, /onAction\?\.\('unlinkProfile'/)
  assert.match(appSource, /if \(type === 'linkProfile'\)/)
  assert.match(appSource, /\.from\('members'\)\s*\.update\(\{ profile_id: profileId \}\)/)
  assert.match(appSource, /if \(type === 'unlinkProfile'\)/)
})

test('groups list can highlight the one expense group linked to pickleball profiles', () => {
  const groupsListSource = readFileSync(new URL('./screens/GroupsList.jsx', import.meta.url), 'utf8')

  assert.match(screenDataSource, /isLinkedPickleballExpenseGroup: Boolean\(linkedPickleballGroupId\)/)
  assert.match(screenDataSource, /linkedPickleballGroupName/)
  assert.match(storeSource, /linkedPickleballGroupId: group\.linked_pickleball_group_id \|\| null/)
  assert.match(groupsListSource, /function isPickleballLikeGroup\(g\) \{/)
  assert.match(groupsListSource, /return g\?\.kind === 'pickleball' \|\| Boolean\(g\?\.isLinkedPickleballExpenseGroup\)/)
  assert.match(groupsListSource, /const linked = g\.isLinkedPickleballExpenseGroup/)
  assert.match(groupsListSource, /const isPickleballGroup = isPickleballLikeGroup\(g\)/)
  assert.match(groupsListSource, /background: isPickleballGroup \? 'linear-gradient\(145deg, rgba\(6,95,70,0\.30\), rgba\(15,23,42,0\.95\)\)' : undefined/)
  assert.match(groupsListSource, /borderColor: isPickleballGroup \? 'rgba\(52,211,153,0\.72\)' : undefined/)
  assert.match(groupsListSource, /Liên kết Pickleball/)
  assert.doesNotMatch(groupsListSource, /Danh bạ chung/)
  assert.doesNotMatch(groupsListSource, /Dùng chung danh bạ với/)
})

test('RLS group id helper includes same-profile expense groups for pickleball members', () => {
  assert.match(profileGroupIdsMigration, /CREATE OR REPLACE FUNCTION public\.get_my_group_ids\(\)/)
  assert.match(profileGroupIdsMigration, /current_actor AS/)
  assert.match(profileGroupIdsMigration, /SELECT id, group_id, profile_id, name/)
  assert.match(profileGroupIdsMigration, /actor\.profile_id IS NOT NULL[\s\S]*m\.profile_id = actor\.profile_id/)
  assert.match(profileGroupIdsMigration, /lower\(m\.name\) = lower\(actor\.name\)/)
  assert.match(profileGroupIdsMigration, /g\.linked_pickleball_group_id = actor\.group_id/)
  assert.match(profileGroupIdsMigration, /m\.is_active IS NOT FALSE/)
})

test('admin group management migration exposes hidden groups and delete access to app admins', () => {
  assert.match(adminGroupManagementMigration, /CREATE OR REPLACE FUNCTION public\.is_expense_group_admin/)
  assert.match(adminGroupManagementMigration, /m\.role IN \('treasurer', 'admin', 'owner'\)/)
  assert.match(adminGroupManagementMigration, /CREATE OR REPLACE FUNCTION public\.get_my_group_ids/)
  assert.match(adminGroupManagementMigration, /actor\.role IN \('admin', 'owner'\)/)
  assert.match(adminGroupManagementMigration, /g\.deleted_at IS NULL/)
  assert.match(adminGroupManagementMigration, /UNION[\s\S]*SELECT group_id FROM admin_groups/)
})

test('expense group RPCs authorize the same profile across duplicate group memberships', () => {
  assert.match(expenseGroupRpcMigration, /WITH current_actor AS/)
  assert.match(expenseGroupRpcMigration, /actor\.profile_id IS NOT NULL[\s\S]*m\.profile_id = actor\.profile_id/)
  assert.match(expenseGroupRpcMigration, /lower\(m\.name\) = lower\(actor\.name\)/)
  assert.match(expenseGroupRpcMigration, /g\.linked_pickleball_group_id IS NOT NULL/)
  assert.match(expenseGroupRpcMigration, /coalesce\(g\.emoji, ''\) NOT IN \('🏓', '🏸'\)/)
})
