import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const storeSource = readFileSync(new URL('./store.jsx', import.meta.url), 'utf8')
const screenDataSource = readFileSync(new URL('./hooks/useScreenData.js', import.meta.url), 'utf8')
const homeSource = readFileSync(new URL('./screens/Home.jsx', import.meta.url), 'utf8')
const settlementSource = readFileSync(new URL('./screens/SettlementPeriod.jsx', import.meta.url), 'utf8')
const settingsSource = readFileSync(new URL('./screens/Settings.jsx', import.meta.url), 'utf8')
const appSource = readFileSync(new URL('./app-v2.jsx', import.meta.url), 'utf8')
const newGroupSource = readFileSync(new URL('./screens/NewGroup.jsx', import.meta.url), 'utf8')
const migrationSource = readFileSync(new URL('../supabase/migrations/20260523000001_profiles_identity.sql', import.meta.url), 'utf8')
const expenseGroupRpcMigration = readFileSync(new URL('../supabase/migrations/20260525000003_expense_group_member_rpcs.sql', import.meta.url), 'utf8')
const memberBillShareMigration = readFileSync(new URL('../supabase/migrations/20260526000001_member_bill_share_tokens.sql', import.meta.url), 'utf8')

test('profiles migration creates central identity and links members', () => {
  assert.match(migrationSource, /CREATE TABLE IF NOT EXISTS public\.profiles/)
  assert.match(migrationSource, /ALTER TABLE public\.members[\s\S]*ADD COLUMN IF NOT EXISTS profile_id uuid/)
  assert.match(migrationSource, /ADD COLUMN IF NOT EXISTS expense_active boolean DEFAULT true/)
  assert.match(migrationSource, /UPDATE public\.members[\s\S]*SET expense_active = false[\s\S]*member_type IN \('casual', 'guest', 'vanglai', 'vãng lai'\)/)
  assert.match(migrationSource, /REFERENCES public\.profiles\(id\)/)
  assert.match(migrationSource, /INSERT INTO public\.profiles/)
  assert.match(migrationSource, /UPDATE public\.members m[\s\S]*SET profile_id = p\.id/)
  assert.match(migrationSource, /ALTER COLUMN profile_id SET NOT NULL/)
  assert.match(migrationSource, /CREATE TRIGGER members_ensure_profile/)
  assert.match(migrationSource, /CREATE POLICY profiles_select/)
  assert.match(migrationSource, /CREATE POLICY profiles_update/)
})

test('member bill share migration creates scoped expiring public tokens', () => {
  assert.match(memberBillShareMigration, /CREATE TABLE IF NOT EXISTS public\.member_bill_share_tokens/)
  assert.match(memberBillShareMigration, /token text NOT NULL UNIQUE/)
  assert.match(memberBillShareMigration, /group_id uuid NOT NULL REFERENCES public\.groups\(id\)/)
  assert.match(memberBillShareMigration, /member_id uuid NOT NULL REFERENCES public\.members\(id\)/)
  assert.match(memberBillShareMigration, /expires_at timestamptz NOT NULL/)
  assert.match(memberBillShareMigration, /created_by uuid REFERENCES public\.members\(id\)/)
  assert.match(memberBillShareMigration, /CREATE OR REPLACE FUNCTION public\.create_member_bill_share_token/)
  assert.match(memberBillShareMigration, /CREATE OR REPLACE FUNCTION public\.get_member_bill_share/)
  assert.match(memberBillShareMigration, /WHERE mbst\.token = p_token[\s\S]*mbst\.expires_at > now\(\)/)
  assert.match(memberBillShareMigration, /jsonb_build_object\([\s\S]*'groupId', v_share\.group_id[\s\S]*'memberId', v_share\.member_id/)
  assert.match(memberBillShareMigration, /REVOKE ALL ON public\.member_bill_share_tokens FROM anon/)
  assert.match(memberBillShareMigration, /GRANT EXECUTE ON FUNCTION public\.get_member_bill_share\(text\) TO anon/)
})

test('store fetches profiles and merges profile fields into members', () => {
  assert.match(storeSource, /profiles:\s*\[\]/)
  assert.match(storeSource, /prR/)
  assert.match(storeSource, /sb\.from\('profiles'\)\.select\('\*'\)/)
  assert.match(storeSource, /profiles:\s*prR\.data \|\| \[\]/)
  assert.match(storeSource, /profiles = \[\]/)
  assert.match(storeSource, /const profilesById = new Map/)
  assert.match(storeSource, /const profile = profilesById\.get\(String\(m\.profile_id \|\| ''\)\)/)
  assert.match(storeSource, /profileId: m\.profile_id/)
  assert.match(storeSource, /name: String\(profile\?\.name \|\| m\.name \|\| ''\)\.trim\(\)/)
  assert.match(storeSource, /bankName: profile\?\.bank_name \|\| m\.bank_name \|\| ''/)
  assert.match(storeSource, /profiles: normalProfiles/)
})

test('ADD_MEMBER can link an existing profile or create a new profile first', () => {
  const addMemberBlock = storeSource.match(/case 'ADD_MEMBER': \{[\s\S]*?return newMember[\s\S]*?\n      \}/)?.[0] || ''
  assert.match(storeSource, /async function ensureProfileForMember\(sb, member\) \{/)
  assert.match(storeSource, /if \(member\?\.profileId \|\| member\?\.profile_id\) return member\.profileId \|\| member\.profile_id/)
  assert.match(storeSource, /\.from\('profiles'\)\s*\.insert\(/)
  assert.match(addMemberBlock, /const profileId = await ensureProfileForMember\(sb, member\)/)
  assert.match(addMemberBlock, /memberInsertRow\(groupId, \{ \.\.\.member, profileId \}, member\.role \|\| 'member'\)/)
})

test('new group flow can include existing profiles', () => {
  assert.match(screenDataSource, /function buildNewGroupData\(state = \{\}\)/)
  assert.match(screenDataSource, /profileOptions: buildProfileOptions\(state\)/)
  assert.match(screenDataSource, /dedupeProfilesFromMembers\(safeArray\(state\?\.members\), profiles\)/)
  assert.match(screenDataSource, /\.filter\(isActiveMember\)/)
  assert.match(newGroupSource, /const \[selectedProfileIds, setSelectedProfileIds\] = useState/)
  assert.match(newGroupSource, /const \[profileQuery, setProfileQuery\] = useState\(''\)/)
  assert.match(newGroupSource, /profileOptions/)
  assert.match(newGroupSource, /filteredProfileOptions/)
  assert.match(newGroupSource, /placeholder="Tìm vài ký tự để lọc thành viên"/)
  assert.match(newGroupSource, /maxHeight: 360/)
  assert.match(newGroupSource, /toggleProfile/)
  assert.match(newGroupSource, /profileIds: selectedProfileIds/)
  assert.match(storeSource, /const profileIds = safeArray\(action\.profileIds \?\? group\.profileIds\)/)
  assert.match(storeSource, /selectedProfiles = profileIds/)
  assert.match(storeSource, /profile_id: selectedProfile\.profileId \|\| selectedProfile\.id/)
})

test('screen data exposes profile aggregation helpers for home and monthly close', () => {
  assert.match(screenDataSource, /function profileIdForMember\(memberId, members\) \{/)
  assert.match(screenDataSource, /function memberIdsForProfile\(profileId, members\) \{/)
  assert.match(screenDataSource, /function aggregateBalancesByProfile\(sourceBalances, members\) \{/)
  assert.match(screenDataSource, /const sourceBalances = buildHomeSourceBalances/)
  assert.match(screenDataSource, /profileBreakdown: aggregateBalancesByProfile\(sourceBalances, members\)/)
  assert.match(screenDataSource, /const monthlySourceBalances = buildMonthlySourceBalances/)
  assert.match(screenDataSource, /profileBreakdown: aggregateBalancesByProfile\(monthlySourceBalances, members\)/)
})

test('home renders source breakdown for the current profile', () => {
  assert.match(screenDataSource, /currentProfileId: profileIdForMember\(currentUserId, members\)/)
  assert.match(screenDataSource, /sourceBreakdown: currentProfileSourceBreakdown\(sourceBalances, currentUserId, members\)/)
  assert.match(screenDataSource, /function currentProfileSourceBreakdown\(sourceBalances, currentUserId, members\) \{/)
  assert.match(homeSource, /<SourceBreakdown sources=\{d\.sourceBreakdown \|\| \[\]\} \/>/)
  assert.match(homeSource, /function SourceBreakdown\(\{ sources \}\) \{/)
  assert.match(homeSource, /Theo nguồn tiền/)
  assert.match(homeSource, /source\.sourceLabel/)
  assert.match(homeSource, /source\.sourceType === 'pickleball'/)
})

test('monthly close renders one profile bill with source breakdown rows', () => {
  assert.match(screenDataSource, /const monthlySourceBalances = buildGlobalMonthlySourceBalances\(state, monthDate\)/)
  assert.match(screenDataSource, /profileBills: buildProfileBillRows\(monthlySourceBalances, members\)/)
  assert.match(screenDataSource, /function buildGlobalMonthlySourceBalances\(state, monthDate\) \{/)
  assert.match(screenDataSource, /function buildProfileBillRows\(sourceBalances, members\) \{/)
  assert.match(settlementSource, /const profileBills = d\.profileBills \|\| \[\]/)
  assert.match(settlementSource, /<ProfileBillList bills=\{profileBills\} \/>/)
  assert.match(settlementSource, /function ProfileBillList\(\{ bills \}\) \{/)
  assert.match(settlementSource, /Bill tổng theo người/)
  assert.match(settlementSource, /bill\.sources\.map/)
})

test('settings exposes profile link management and app updates membership profile ids', () => {
  assert.match(screenDataSource, /profileSync: buildProfileSyncData\(state, me\)/)
  assert.match(screenDataSource, /function buildProfileSyncData\(state, me\) \{/)
  assert.match(settingsSource, /const profileSync = d\.profileSync/)
  assert.match(settingsSource, /Danh bạ liên thông/)
  assert.match(settingsSource, /profileSync\.linkedMemberships\.map/)
  assert.match(settingsSource, /profileSync\.candidates\.map/)
  assert.match(settingsSource, /onAction\?\.\('linkProfile'/)
  assert.match(settingsSource, /onAction\?\.\('unlinkProfile'/)
  assert.match(appSource, /if \(type === 'linkProfile'\)/)
  assert.match(appSource, /\.from\('members'\)\s*\.update\(\{ profile_id: profileId \}\)/)
  assert.match(appSource, /if \(type === 'unlinkProfile'\)/)
})

test('groups list can highlight the one expense group linked to pickleball profiles', () => {
  const groupsListSource = readFileSync(new URL('./screens/GroupsList.jsx', import.meta.url), 'utf8')

  assert.match(screenDataSource, /isLinkedPickleballExpenseGroup: Boolean\(linkedPickleballGroupId\)/)
  assert.match(screenDataSource, /linkedPickleballGroupName/)
  assert.match(storeSource, /linkedPickleballGroupId: group\.linked_pickleball_group_id \|\| null/)
  assert.match(groupsListSource, /const linked = g\.isLinkedPickleballExpenseGroup/)
  assert.match(groupsListSource, /Liên kết Pickleball/)
  assert.match(groupsListSource, /Dùng chung danh bạ với/)
})

test('expense group RPCs authorize the same profile across duplicate group memberships', () => {
  assert.match(expenseGroupRpcMigration, /WITH current_actor AS/)
  assert.match(expenseGroupRpcMigration, /actor\.profile_id IS NOT NULL[\s\S]*m\.profile_id = actor\.profile_id/)
  assert.match(expenseGroupRpcMigration, /lower\(m\.name\) = lower\(actor\.name\)/)
  assert.match(expenseGroupRpcMigration, /g\.linked_pickleball_group_id IS NOT NULL/)
  assert.match(expenseGroupRpcMigration, /coalesce\(g\.emoji, ''\) NOT IN \('🏓', '🏸'\)/)
})
